service: chakri-chai-backend

frameworkVersion: "3"

provider:
  name: aws
  region: ap-south-1
  runtime: nodejs18.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
        - ses:SendEmail
      Resource: "*"

functions:

  login:
    handler: auth/login.handler
    events:
      - http:
          path: /auth/login
          method: POST
          cors: true

  forgotpassword:
    handler: auth/forgotpassword.handler
    events:
      - http:
          path: /auth/forgotpassword
          method: POST
          cors: true

  verifyotp:
    handler: auth/verifyotp.handler
    events:
      - http:
          path: /auth/verifyotp
          method: POST
          cors: true
  
  refresh:
    handler: auth/refresh.handler
    events:
      - http:
          path: /auth/refresh
          method: POST
          cors: true

  createjob:
    handler: jobs/createjob.handler
    events:
      - http:
          path: /jobs/createjob
          method: POST
          cors: true

  getjob:
    handler: jobs/getjob.handler
    events:
      - http:
          path: /jobs/getjob
          method: POST
          cors: true
  
  joblist:
    handler: jobs/joblist.handler
    events:
      - http:
          path: /jobs/joblist
          method: POST
          cors: true
  
  jobpostings:
    handler: jobs/jobpostings.handler
    events:
      - http:
          path: /jobs/jobpostings
          method: POST
          cors: true

  toggleactivestatus:
    handler: jobs/toggleactivestatus.handler
    events:
      - http:
          path: /jobs/toggleactivestatus
          method: POST
          cors: true

resources:
  Resources:
    JobDetails:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: JobDetails
        AttributeDefinitions:
          - AttributeName: JOB_ID
            AttributeType: S
        KeySchema:
          - AttributeName: JOB_ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    
    UserInformation:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserInformation
        AttributeDefinitions:
          - AttributeName: EMAIL_ID
            AttributeType: S
        KeySchema:
          - AttributeName: EMAIL_ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    ApplicationDetails:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ApplicationDetails
        AttributeDefinitions:
          - AttributeName: APPLICATION_ID
            AttributeType: S
        KeySchema:
          - AttributeName: APPLICATION_ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    
    RefreshTokenDetails:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: RefreshTokenDetails
        AttributeDefinitions:
          - AttributeName: TOKEN_ID
            AttributeType: S
        KeySchema:
          - AttributeName: TOKEN_ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    OTPDetails:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: OTPDetails
        AttributeDefinitions:
          - AttributeName: SESSION_ID
            AttributeType: S
        KeySchema:
          - AttributeName: SESSION_ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5


